t = 0:0.001:1;
A = 5;
f = 5;
sigma = 1.5;
U1 = 3;
U2 = 2;
s = A*sin(2*pi*f*t);
x = s + sigma*randn(size(t));
filtered = x;
filtered(abs(filtered) < U2) = 0;
selected = abs(x) > U1;
maxLocations = x == max(x);
minLocations = x == min(x);
low = min([x filtered -U1 -U2 0]) - 1;
high = max([x filtered U1 U2 0]) + 1;

figure(1);
subplot(1, 2, 1);
h1 = plot(t, x, 'b-', 'LineWidth', 1.25);
hold on;
h2 = plot(t, filtered, 'k--', 'LineWidth', 1.25);
h3 = plot([t(1) t(end)], [U1 U1], 'r-');
plot([t(1) t(end)], [-U1 -U1], 'r-');
h4 = plot([t(1) t(end)], [U2 U2], 'm:');
plot([t(1) t(end)], [-U2 -U2], 'm:');
xlabel('Time (s)');
ylabel('Voltage (V)');
title('Original and filtered signals', 'Color', 'b', 'FontSize', 14);
legend([h1 h2 h3 h4], {'Original', 'Filtered', 'U1', 'U2'}, 'Location', 'best');
grid on;
axis([t(1) t(end) low high]);

subplot(1, 2, 2);
h5 = stem(t(selected), x(selected), 'b');
hold on;
h6 = plot(t(maxLocations), x(maxLocations), 'go', 'MarkerFaceColor', 'g');
h7 = plot(t(minLocations), x(minLocations), 'mv', 'MarkerFaceColor', 'm');
xlabel('Time (s)');
ylabel('Voltage (V)');
title('Signal values above the threshold', 'Color', 'b', 'FontSize', 14);
legend([h5 h6 h7], {'Above U1', 'Maximum', 'Minimum'}, 'Location', 'best');
grid on;
axis([t(1) t(end) low high]);
